### ISSUE TITLE
Accept "Pay to Promote" payments through Stripe

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/Campaigns#100]
I added a payment processing page to the Campaigns site:
https://campaigns.wevote.us/c/jennifer-mcclellan-for-governor-of-virginia/pay-to-promote

This is the file I added, and it uses the same structure as the Membership page you created.
/Campaigns/src/js/pages/CampaignSupport/CampaignSupportPayToPromoteProcess.jsx

Please add a new Stripe way "chip in" to a particular campaign. We need it to be distinct from voter donations, memberships, and premium plans for endorsers.

Please also see: https://github.com/wevote/WeVoteServer/issues/1657

Previous Design notes:
- https://docs.google.com/document/d/1cAIoODsTkOyaILV-8JmjIMCYyTrfwyDdImvQlgfZfN8/edit#heading=h.e66z99drydr6
- https://docs.google.com/document/d/1oPA7ykoYFIoiI9sMwHT3UKrjrEIOq6M3HhZ4rxIZ5cw/edit

**Comment by SailingSteve** [comment]
I really think red is the wrong color to indicate an affirmative choice, it usually indicates danger.

<img width="737" alt="Screen Shot 2021-07-07 at 10 33 24 AM" src="https://user-images.githubusercontent.com/6923653/124804338-09643e00-df0f-11eb-8705-3de052b42bdd.png">

How about:

<img width="339" alt="Screen Shot 2021-07-07 at 11 19 14 AM" src="https://user-images.githubusercontent.com/6923653/124809681-3ca9cb80-df15-11eb-90b2-34ef69e1c652.png">

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, good point. Feel free to update the $$ selection colors to the We Vote button blue.

**Comment by SailingSteve** [comment]
Color change done.  Thanks.

**Comment by SailingSteve** [comment]
1) Donations and Chipins are one time stripe payments, and membership and premium plans are stripe subscriptions that will bill monthly if a membership, or quarterly/half year/annually if a premium plan.
2) For Chipins we want to be able to filter by donor and by the campaign that they are chipping into.

**Comment by SailingSteve** [comment]
@DaleMcGrew Question:
I'm struggling to name the payments in the stripe history display. (Which is probably the root for why the variable names got confused.)
The way it is now:
      // "One Time" donation to WeVote via WebApp
      // "Subscription" Monthly payment for donations to WeVote via WebApp
      // "Chip in" is a one time donation for Campaigns and is promised for targeted advertisements
      // "Membership" is a monthly payment of a donation subscription for Campaigns for unrestricted use
      // "Subscription Plan" is our premium plan for customization for Organizations

Is "premium" just a word for us to indicate that they are buying a better service, or can the publicly visible "Subscription Plan" be renamed to "Premium Plan"?  Premium meaning better.  Premium also has a troublesome secondary meaning like "Why pay a big premium for a Lexus, when you could buy a Toyota?"

Or rename "Subscription" in WebApp to be "Membership", then there would be no distinction between stripe subscriptions for the two apps.  

Or rename "Subscription" in WebApp to be "Monthly Subscription", and you could subscribe to both, although that is just a distinction in naming, cause you can have as many stripe subscriptions to each that you want.

**Comment by DaleMcGrew** [comment]
Hi Steve, I created this Google doc with some thoughts, and for further discussion: https://docs.google.com/document/d/1oN8G0LlTD8Iz4L5jNWdc3nzwmVl11FAn9GFTBZF6H9A/edit
