### ISSUE TITLE
Upload Photo connect to Photo Library and Camera

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/Campaigns#32]
When using an actual mobile phone, we want to let people choose a photo from their phone's image library, or take a photo with their camera. This *may* work already with the component we are using, and needs to be tested. This is the starting page: 
http://localhost:3000/start-a-campaign-add-photo

<img width="319" alt="Screen Shot 2021-02-22 at 4 15 51 PM" src="https://user-images.githubusercontent.com/7756031/108786900-84f9bb80-7529-11eb-8eb8-2e455a34ff47.png">

...and this are the options to offer:
![Screen Shot 2021-02-22 at 4 19 11 PM](https://user-images.githubusercontent.com/7756031/108787027-c0948580-7529-11eb-99dc-519ead3b10ce.png)

**Comment by SailingSteve** [comment]
start ngrok
http:
    stevepodell@Steves-MacBook-Pro-32GB-Oct-2109 ngrok % ./ngrok http 3000
https:
    stevepodell@Steves-MacBook-Pro-32GB-Oct-2109 ngrok % ./ngrok http https://localhost:3000

I used https:

    ngrok by @inconshreveable                                                                                                                   (Ctrl+C to quit)
                                                                                                                                                            
    Session Status                online                                                                                                                        
    Account                        (Plan: Free)                                                                                                                 
    Version                       2.3.35                                                                                                                        
    Region                        United States (us)                                                                                                            
    Web Interface                 http://127.0.0.1:4040                                                                                                         
    Forwarding                    http://316caa1ce659.ngrok.io -> https://localhost:3000                                                                        
    Forwarding                    https://316caa1ce659.ngrok.io -> https://localhost:3000     

Airdrop the url  `https://316caa1ce659.ngrok.io` to your phone.
The app should start right up.

**Comment by SailingSteve** [comment]
If you get a "headers" error, then...

<img width="1469" alt="Screen Shot 2021-02-24 at 4 48 27 PM" src="https://user-images.githubusercontent.com/6923653/109086326-3a5e7780-76c0-11eb-877c-e1e28acb066b.png">


You need that disableHostCheck on line 97 of webpack.config.js (I'll check it in on my next PR)

**Comment by SailingSteve** [comment]
@DaleMcGrew  These are in reverse order, but you can take pictures, and load photos from your "photo library" in both Safari and Chrome on iOS.  The existing code works perfectly.

![IMG_0145](https://user-images.githubusercontent.com/6923653/109086557-a50fb300-76c0-11eb-9b56-9292a0881d0b.PNG)
![IMG_0144](https://user-images.githubusercontent.com/6923653/109086563-a80aa380-76c0-11eb-8164-91a1e708145c.PNG)
![IMG_0143](https://user-images.githubusercontent.com/6923653/109086605-bf499100-76c0-11eb-91a2-c3075e4a2c76.PNG)
![IMG_0142](https://user-images.githubusercontent.com/6923653/109086606-bfe22780-76c0-11eb-9c78-1df1b2b485e3.PNG)
![IMG_0141](https://user-images.githubusercontent.com/6923653/109086610-c2448180-76c0-11eb-86b6-a77486cbbf74.PNG)
![IMG_0140](https://user-images.githubusercontent.com/6923653/109086615-c4a6db80-76c0-11eb-8052-c9ce7bc7901d.PNG)

**Comment by DaleMcGrew** [comment]
That is so excellent @SailingSteve! I love the react packages community! Thank you for investigating.
