### ISSUE TITLE
Static name needed for initial/root bundle

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/Campaigns#62]
We will be changing the Campaigns index.html file to be generated by our API server, so we can use variables within index.html. To follow this approach, we need to be able to use a static name for the first Campaigns bundle which is loaded.

Please change the name of the initial/root bundle to "main.campaigns.js".
(as opposed to "main.bce5883a8abc30005202.js")
All other bundles should continue to follow the `[name].[contenthash].js` pattern.

**Comment by SailingSteve** [comment]
What variables are being set by the API server when it generates the index.html?

Dale McGrew  9:23 AM
The quick answer is custom favicon, social share images and text, custom google analytics. The full answer can be found by searching “chosen_” in WeVoteServer/templates/organization/organization_index.html (this is the version for the WebApp site, but it will guide us in updating the index page for Campaigns.)

Steve Podell  9:42 AM
It looks like changes made to the webapp index.html don’t automatically end up in the output from organization_index.html — Do they have to be manually synchronized?
9:44
Why not have the WeVoteServer pull the WebApp index.html from git, and make the few changes it needs — then they would always be synchronized?

**Comment by DaleMcGrew** [comment]
Great solution!
