### ISSUE TITLE
Add Contacts: Retrieving raw data

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/Campaigns#63]
We would like to support a few ways of bulk importing friend contact information.

The start of the interface is here:
https://projects.invisionapp.com/d/main?origin=v7#/console/21000140/442831992/preview?scrollOffset=1268

We will support:
A) "Add contacts from phone" (Mobile only)
Ask permission from the voter to open their contacts and return the file to the API server. Once we do that we can discuss another issue about how to process that data.

B) "Add from Google contacts"

C) "Add contacts from file" (Desktop only)

D+) Other options?

**Comment by SailingSteve** [comment]
It looks like iPhone/Android contacts are not available to JavaScript apps, only native (or Cordova) apps. (It kind of makes sense!)
https://web.dev/contact-picker/
https://github.com/apache/cordova-plugin-contacts

**Comment by SailingSteve** [comment]
Google contacts are probably available via https://developers.google.com/people
I personally have 3 Google contacts:  all are more than 4 years old.
https://contacts.google.com/

**Comment by SailingSteve** [comment]
Apple has slightly more users than Android in the US, but last year our logins with Facebook were overwhelmingly Apple... from memory, I remember 90% apple.  I'll try and find that stat.  But in any case, a Google solution is not likely to have great coverage.

**Comment by SailingSteve** [comment]
@DaleMcGrew 

A) It looks like import from a webapp is not possible (anymore), or at least without a native or Cordova app.  Do you have an example of it working today on some other site?

B) Google Contacts, is doable, but who uses it?

C) We would have them export their contacts to a file, then upload it?  Seems too complicated -- who would do this?

D) There is twitter friends and facebook friends like the webapp... does this still work?

**Comment by DaleMcGrew** [comment]
Thank you for the solution to Google Contacts @SailingSteve.
